export type IntegStatus = 'healthy' | 'degraded' | 'planned';
export type IntegCategory = 'government' | 'ai' | 'communications' | 'payments' | 'infrastructure' | 'planned';
export type DataDir = 'inbound' | 'outbound' | 'bidirectional';

export interface Integration {
  id: string;
  name: string;
  subtitle: string;
  category: IntegCategory;
  status: IntegStatus;
  direction: DataDir;
  responseTime: string;
  responseOk: boolean; // true = emerald, false = amber/red
  responseAlert?: boolean; // >3s = red pulsing
  uptime: string;
  version: string;
  endpoint: string;
  todayStat: string;
  lastCheck: string;
  logoLetter: string;
  logoColor: string;
  callsToday: string;
  errorsToday: number;
  degradedNote?: string;
  special?: string;
  special2?: string;
  plannedDate?: string;
  plannedDesc?: string;
  plannedNote?: string;
}

export const CATEGORY_META: Record<IntegCategory, { label: string; color: string; hex: string }> = {
  government:     { label: 'Government / Regulatory', color: 'teal',    hex: '#2DD4BF' },
  ai:             { label: 'AI / Intelligence',        color: 'violet',  hex: '#A78BFA' },
  communications: { label: 'Communications',           color: 'blue',    hex: '#60A5FA' },
  payments:       { label: 'Payments',                 color: 'emerald', hex: '#34D399' },
  infrastructure: { label: 'Infrastructure',           color: 'slate',   hex: '#94A3B8' },
  planned:        { label: 'Future / Planned',         color: 'blue',    hex: '#93C5FD' },
};

export const CATEGORY_ORDER: IntegCategory[] = [
  'government', 'ai', 'communications', 'payments', 'infrastructure', 'planned',
];

export const INTEGRATIONS: Integration[] = [
  {
    id: 'nabidh',
    name: 'Nabidh HIE',
    subtitle: 'National Health Information Exchange · DHA · Dubai',
    category: 'government',
    status: 'healthy',
    direction: 'bidirectional',
    responseTime: '0.29s',
    responseOk: true,
    uptime: '99.97%',
    version: 'FHIR R4/4.0.1',
    endpoint: 'api.nabidh.dha.gov.ae/fhir/r4',
    todayStat: '12,847 records synced today',
    lastCheck: '12s ago',
    logoLetter: 'N',
    logoColor: '#2DD4BF',
    callsToday: '12,847',
    errorsToday: 0,
    special: 'NABIDH-VENDOR-2024-00847',
    special2: 'DHA Critical Integration',
  },
  {
    id: 'dha-rx',
    name: 'DHA ePrescription',
    subtitle: 'Digital Prescription Signing · DHA',
    category: 'government',
    status: 'healthy',
    direction: 'outbound',
    responseTime: '0.34s',
    responseOk: true,
    uptime: '99.99%',
    version: 'DHA-RX-API v3.2',
    endpoint: 'erx.dha.gov.ae/api/v3',
    todayStat: '2,134 prescriptions signed today',
    lastCheck: '8s ago',
    logoLetter: 'DHA',
    logoColor: '#2DD4BF',
    callsToday: '2,134',
    errorsToday: 0,
  },
  {
    id: 'dha-reporting',
    name: 'DHA Reporting API',
    subtitle: 'Compliance Data Submission · DHA',
    category: 'government',
    status: 'healthy',
    direction: 'outbound',
    responseTime: '0.89s',
    responseOk: true,
    uptime: '99.94%',
    version: 'DHA-REPORT v2.1',
    endpoint: 'reporting.dha.gov.ae/api/v2',
    todayStat: '47 reports submitted today',
    lastCheck: '1h ago',
    logoLetter: 'DHA',
    logoColor: '#2DD4BF',
    callsToday: '47',
    errorsToday: 0,
  },
  {
    id: 'uae-pass',
    name: 'UAE PASS',
    subtitle: 'National Identity Verification',
    category: 'government',
    status: 'healthy',
    direction: 'outbound',
    responseTime: '0.41s',
    responseOk: true,
    uptime: '99.91%',
    version: 'UAE PASS v2.1',
    endpoint: 'api.uaepass.ae/idshub/v2',
    todayStat: '847 verifications today',
    lastCheck: '3s ago',
    logoLetter: '🇦🇪',
    logoColor: '#34D399',
    callsToday: '847',
    errorsToday: 0,
  },
  {
    id: 'mohap',
    name: 'MOHAP Drug Formulary',
    subtitle: 'Registered Drug Database · MOHAP',
    category: 'government',
    status: 'healthy',
    direction: 'inbound',
    responseTime: '1.2s (batch)',
    responseOk: false,
    uptime: '99.84%',
    version: 'MOHAP-FORM v1.8',
    endpoint: 'formulary.mohap.gov.ae/api',
    todayStat: '48,291 drugs in registry',
    lastCheck: 'Today 3:00 AM',
    logoLetter: 'MH',
    logoColor: '#60A5FA',
    callsToday: '1',
    errorsToday: 0,
  },
  {
    id: 'tatmeen',
    name: 'Tatmeen',
    subtitle: 'Pharmaceutical Track & Trace · MOHAP',
    category: 'government',
    status: 'healthy',
    direction: 'bidirectional',
    responseTime: '1.8s',
    responseOk: false,
    uptime: '99.61%',
    version: 'Tatmeen API v2.0',
    endpoint: 'api.tatmeen.gov.ae/v2',
    todayStat: '1,247 queries · 0 recalls today',
    lastCheck: '24s ago',
    logoLetter: 'T',
    logoColor: '#FCD34D',
    callsToday: '1,247',
    errorsToday: 0,
  },
  {
    id: 'shafafiya',
    name: 'Shafafiya',
    subtitle: 'Insurance Claims Processing · DHA',
    category: 'government',
    status: 'degraded',
    direction: 'bidirectional',
    responseTime: '3.2s',
    responseOk: false,
    responseAlert: true,
    uptime: '99.81%',
    version: 'Shafafiya v3.0',
    endpoint: 'shafafiya.dha.gov.ae/api/v3',
    todayStat: '1,032 claims processed today',
    lastCheck: '2s ago',
    logoLetter: 'S',
    logoColor: '#F59E0B',
    callsToday: '1,032',
    errorsToday: 0,
    degradedNote: 'Degraded since 1:20 PM · Daman upstream issue',
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    subtitle: 'AI Health Assistant · Clinical · Insurance',
    category: 'ai',
    status: 'healthy',
    direction: 'bidirectional',
    responseTime: '2.3s',
    responseOk: false,
    uptime: '99.99%',
    version: 'claude-sonnet-4-20250514',
    endpoint: 'api.anthropic.com/v1',
    todayStat: '8,921 sessions · AED 612 today',
    lastCheck: '1s ago',
    logoLetter: 'A',
    logoColor: '#A78BFA',
    callsToday: '8,921',
    errorsToday: 0,
    special: 'Patient data never sent to Anthropic for training. Conversations anonymized in CeenAiX middleware.',
  },
  {
    id: 'icd10',
    name: 'ICD-10 / SNOMED CT',
    subtitle: 'Diagnosis Coding & Clinical Terminology',
    category: 'ai',
    status: 'healthy',
    direction: 'inbound',
    responseTime: '0.18s',
    responseOk: true,
    uptime: '99.99%',
    version: 'ICD-10-CM 2026 + SNOMED Jan 2026',
    endpoint: 'clinicaltables.nlm.nih.gov/api',
    todayStat: '4,891 lookups today',
    lastCheck: '4s ago',
    logoLetter: 'ICD',
    logoColor: '#A78BFA',
    callsToday: '4,891',
    errorsToday: 0,
  },
  {
    id: 'twilio',
    name: 'Twilio',
    subtitle: 'SMS Gateway · Global',
    category: 'communications',
    status: 'healthy',
    direction: 'outbound',
    responseTime: '0.52s',
    responseOk: true,
    uptime: '99.95%',
    version: 'Twilio API v2010',
    endpoint: 'api.twilio.com/2010-04-01',
    todayStat: '3,847 SMS · AED 76 today',
    lastCheck: '7s ago',
    logoLetter: 'T',
    logoColor: '#F87171',
    callsToday: '3,847',
    errorsToday: 0,
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp Business',
    subtitle: 'Patient Messaging · Meta',
    category: 'communications',
    status: 'healthy',
    direction: 'bidirectional',
    responseTime: '0.61s',
    responseOk: true,
    uptime: '99.89%',
    version: 'WhatsApp Cloud API v18',
    endpoint: 'graph.facebook.com/v18.0',
    todayStat: '1,247 messages today',
    lastCheck: '11s ago',
    logoLetter: 'W',
    logoColor: '#34D399',
    callsToday: '1,247',
    errorsToday: 0,
  },
  {
    id: 'sendgrid',
    name: 'SendGrid',
    subtitle: 'Transactional Email · Twilio',
    category: 'communications',
    status: 'healthy',
    direction: 'outbound',
    responseTime: '0.34s',
    responseOk: true,
    uptime: '99.97%',
    version: 'SendGrid API v3',
    endpoint: 'api.sendgrid.com/v3',
    todayStat: '2,341 emails · 99.2% delivery',
    lastCheck: '14s ago',
    logoLetter: 'SG',
    logoColor: '#60A5FA',
    callsToday: '2,341',
    errorsToday: 0,
  },
  {
    id: 'firebase',
    name: 'Firebase',
    subtitle: 'Push Notifications · Google',
    category: 'communications',
    status: 'healthy',
    direction: 'outbound',
    responseTime: '0.29s',
    responseOk: true,
    uptime: '99.98%',
    version: 'FCM v1',
    endpoint: 'fcm.googleapis.com/v1',
    todayStat: '12,847 push · 94.1% delivery',
    lastCheck: '3s ago',
    logoLetter: 'F',
    logoColor: '#FB923C',
    callsToday: '12,847',
    errorsToday: 0,
  },
  {
    id: 'network-intl',
    name: 'Network International',
    subtitle: 'UAE Payment Gateway',
    category: 'payments',
    status: 'healthy',
    direction: 'bidirectional',
    responseTime: '0.89s',
    responseOk: true,
    uptime: '99.93%',
    version: 'N-Genius v2.3',
    endpoint: 'api.ngenius-payments.com/v1',
    todayStat: '312 transactions · AED 124,800',
    lastCheck: '5s ago',
    logoLetter: 'NI',
    logoColor: '#34D399',
    callsToday: '312',
    errorsToday: 0,
    special: 'PCI-DSS Level 1',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    subtitle: 'International Card Processing',
    category: 'payments',
    status: 'healthy',
    direction: 'bidirectional',
    responseTime: '0.71s',
    responseOk: true,
    uptime: '99.98%',
    version: 'Stripe API 2024-09-30',
    endpoint: 'api.stripe.com/v1',
    todayStat: '47 international transactions today',
    lastCheck: '18s ago',
    logoLetter: 'S',
    logoColor: '#818CF8',
    callsToday: '47',
    errorsToday: 0,
  },
  {
    id: 'aws',
    name: 'AWS UAE',
    subtitle: 'Cloud Hosting · AE-EAST-1',
    category: 'infrastructure',
    status: 'healthy',
    direction: 'bidirectional',
    responseTime: '12ms',
    responseOk: true,
    uptime: '99.99%',
    version: 'AWS SDK v3',
    endpoint: 'ae-east-1.amazonaws.com',
    todayStat: 'EC2 · S3 · RDS · Lambda · CloudFront',
    lastCheck: '1s ago',
    logoLetter: 'AWS',
    logoColor: '#FB923C',
    callsToday: 'Internal',
    errorsToday: 0,
    special: 'Data residency: UAE AE-EAST-1',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    subtitle: 'CDN + DDoS Protection',
    category: 'infrastructure',
    status: 'healthy',
    direction: 'inbound',
    responseTime: '8ms',
    responseOk: true,
    uptime: '100%',
    version: 'Cloudflare API v4',
    endpoint: 'api.cloudflare.com/client/v4',
    todayStat: '99.8% cache hit · DDoS: Active',
    lastCheck: '2s ago',
    logoLetter: 'CF',
    logoColor: '#FB923C',
    callsToday: 'Passive',
    errorsToday: 0,
  },
  {
    id: 'mongodb',
    name: 'MongoDB Atlas',
    subtitle: 'Database Cluster · UAE Region',
    category: 'infrastructure',
    status: 'healthy',
    direction: 'bidirectional',
    responseTime: '24ms',
    responseOk: true,
    uptime: '99.98%',
    version: 'Atlas 7.0',
    endpoint: 'cluster0.mongodb.net (UAE)',
    todayStat: '847GB · 3-node replica',
    lastCheck: '1s ago',
    logoLetter: 'MDB',
    logoColor: '#4ADE80',
    callsToday: 'Internal',
    errorsToday: 0,
  },
  {
    id: 'redis',
    name: 'Redis',
    subtitle: 'Caching Layer',
    category: 'infrastructure',
    status: 'healthy',
    direction: 'bidirectional',
    responseTime: '2ms',
    responseOk: true,
    uptime: '99.99%',
    version: 'Redis 7.2',
    endpoint: 'redis.ceenaix.internal:6379',
    todayStat: '94.7% cache hit · 8.4/16GB',
    lastCheck: '1s ago',
    logoLetter: 'R',
    logoColor: '#F87171',
    callsToday: 'Internal',
    errorsToday: 0,
  },
  {
    id: 'datadog',
    name: 'Datadog',
    subtitle: 'Monitoring & APM',
    category: 'infrastructure',
    status: 'healthy',
    direction: 'outbound',
    responseTime: '18ms',
    responseOk: true,
    uptime: '99.99%',
    version: 'Datadog API v2',
    endpoint: 'api.datadoghq.com/api/v2',
    todayStat: '1.2M APM traces · 48GB logs',
    lastCheck: '1s ago',
    logoLetter: 'D',
    logoColor: '#C084FC',
    callsToday: '1.2M',
    errorsToday: 0,
  },
  {
    id: 'malaffi',
    name: 'Malaffi HIE',
    subtitle: 'Abu Dhabi Health Records · SEHA',
    category: 'planned',
    status: 'planned',
    direction: 'bidirectional',
    responseTime: '—',
    responseOk: true,
    uptime: '—',
    version: '—',
    endpoint: '—',
    todayStat: 'Application submitted 15 Mar 2026',
    lastCheck: '—',
    logoLetter: 'M',
    logoColor: '#60A5FA',
    callsToday: '0',
    errorsToday: 0,
    plannedDate: 'Q3 2026',
    plannedDesc: 'Abu Dhabi national HIE. Enables CeenAiX expansion to Abu Dhabi. Vendor approval pending.',
    plannedNote: 'Submitted: 15 Mar 2026 · ETA: Sep 2026',
  },
  {
    id: 'riayati',
    name: 'Riayati',
    subtitle: 'National Medical Records · MOH',
    category: 'planned',
    status: 'planned',
    direction: 'bidirectional',
    responseTime: '—',
    responseOk: true,
    uptime: '—',
    version: '—',
    endpoint: '—',
    todayStat: 'Planning phase',
    lastCheck: '—',
    logoLetter: 'R',
    logoColor: '#60A5FA',
    callsToday: '0',
    errorsToday: 0,
    plannedDate: 'Q4 2026',
    plannedDesc: 'UAE national medical records (MOH). Connects patients across all 7 emirates.',
  },
  {
    id: 'ehs',
    name: 'Emirates Health Services',
    subtitle: 'Abu Dhabi Public Healthcare · EHS',
    category: 'planned',
    status: 'planned',
    direction: 'bidirectional',
    responseTime: '—',
    responseOk: true,
    uptime: '—',
    version: '—',
    endpoint: '—',
    todayStat: 'Pre-planning phase',
    lastCheck: '—',
    logoLetter: 'EHS',
    logoColor: '#60A5FA',
    callsToday: '0',
    errorsToday: 0,
    plannedDate: 'Q1 2027',
    plannedDesc: 'Abu Dhabi public healthcare system integration.',
  },
];
