import type { LabSample, ImagingStudy } from './types';

export const mockSamples: LabSample[] = [
  {
    id: 'LAB-20260407-002847',
    patientName: 'Ibrahim Al Marzouqi',
    patientAge: '55',
    patientGender: 'M',
    bloodType: 'O+',
    patientId: 'PT-Unknown',
    insurance: 'Oman Insurance',
    doctor: 'Dr. Maryam Al Sayed',
    clinic: 'Al Zahra Clinic',
    tests: ['K+', 'Na+', 'Cl-', 'HCO3-'],
    priority: 'STAT',
    status: 'Resulted',
    collectedAt: '11:30 AM',
    receivedAt: '11:47 AM',
    tat: '2h 37m',
    tech: 'Fatima AR',
    isCritical: true,
    criticalValue: 'K+ 6.8 mEq/L ↑↑',
    department: 'Chemistry',
  },
  {
    id: 'LAB-20260407-003891',
    patientName: 'Aisha Mohammed',
    patientAge: '42',
    patientGender: 'F',
    bloodType: 'O-',
    patientId: 'PT-006',
    insurance: 'AXA Gulf Standard',
    doctor: 'Dr. Ahmed Al Rashidi',
    clinic: 'Al Noor Medical Center',
    tests: ['BNP', 'Electrolytes', 'Renal Function'],
    priority: 'Urgent',
    status: 'Received',
    collectedAt: '2:00 PM',
    receivedAt: '2:05 PM',
    tat: '5m',
    tech: 'Unassigned',
    department: 'Chemistry',
  },
  {
    id: 'LAB-20260407-003241',
    patientName: 'Mohammed Al Shamsi',
    patientAge: '48',
    patientGender: 'M',
    bloodType: 'A+',
    patientId: 'PT-018',
    insurance: 'Daman',
    doctor: 'Dr. Khalid Al Nasser',
    clinic: 'Burjeel Hospital',
    tests: ['Troponin', 'BNP', 'Lipid Panel', 'CBC'],
    priority: 'Urgent',
    status: 'In Progress',
    collectedAt: '1:00 PM',
    receivedAt: '1:12 PM',
    tat: '1h 5m',
    tech: 'Ali Hassan',
    department: 'Chemistry',
  },
  {
    id: 'LAB-20260407-003102',
    patientName: 'Sara Al Khalili',
    patientAge: '34',
    patientGender: 'F',
    bloodType: 'B+',
    patientId: 'PT-024',
    insurance: 'MetLife',
    doctor: 'Dr. Hana Al Farsi',
    clinic: 'Saudi German Hospital',
    tests: ['CBC', 'ESR'],
    priority: 'Routine',
    status: 'Verified',
    collectedAt: '9:00 AM',
    receivedAt: '9:15 AM',
    tat: '3h 20m',
    tech: 'Fatima AR',
    department: 'Haematology',
  },
  {
    id: 'LAB-20260407-002991',
    patientName: 'Yousuf Al Zaabi',
    patientAge: '61',
    patientGender: 'M',
    bloodType: 'AB+',
    patientId: 'PT-031',
    insurance: 'Thiqa',
    doctor: 'Dr. Rashed Al Blooshi',
    clinic: 'Cleveland Clinic Abu Dhabi',
    tests: ['HbA1c', 'FBS', 'Lipid Panel'],
    priority: 'Routine',
    status: 'Released',
    collectedAt: '8:30 AM',
    receivedAt: '8:45 AM',
    tat: '4h 10m',
    tech: 'Omar Said',
    department: 'Chemistry',
  },
  {
    id: 'LAB-20260407-003450',
    patientName: 'Mariam Al Suwaidi',
    patientAge: '29',
    patientGender: 'F',
    bloodType: 'A-',
    patientId: 'PT-041',
    insurance: 'Daman Enhanced',
    doctor: 'Dr. Layla Al Hashimi',
    clinic: 'City Hospital Dubai',
    tests: ['PT', 'aPTT', 'INR', 'Fibrinogen'],
    priority: 'Urgent',
    status: 'Accessioned',
    collectedAt: '1:45 PM',
    receivedAt: '1:58 PM',
    tat: '29m',
    tech: 'Fatima AR',
    department: 'Coagulation',
  },
  {
    id: 'LAB-20260407-003567',
    patientName: 'Hassan Al Mansoori',
    patientAge: '52',
    patientGender: 'M',
    bloodType: 'O+',
    patientId: 'PT-055',
    insurance: 'Oman Insurance',
    doctor: 'Dr. Fatima Al Mansoori',
    clinic: 'Al Noor Medical Center',
    tests: ['Culture & Sensitivity', 'Gram Stain'],
    priority: 'Urgent',
    status: 'In Progress',
    collectedAt: '10:00 AM',
    receivedAt: '10:20 AM',
    tat: '4h 7m',
    tech: 'Nour Saleh',
    department: 'Microbiology',
  },
  {
    id: 'LAB-20260407-003612',
    patientName: 'Fatima Ibrahim',
    patientAge: '31',
    patientGender: 'F',
    bloodType: 'B-',
    patientId: 'PT-062',
    insurance: 'AXA Gulf',
    doctor: 'Dr. Mariam Al Farsi',
    clinic: 'City Hospital Dubai',
    tests: ['Urinalysis', 'Urine Culture'],
    priority: 'Routine',
    status: 'Pending Verify',
    collectedAt: '11:00 AM',
    receivedAt: '11:15 AM',
    tat: '3h 12m',
    tech: 'Ali Hassan',
    department: 'Urinalysis',
  },
];

export const mockStudies: ImagingStudy[] = [
  {
    accession: 'MRI-20260407-001',
    patientName: 'Sarah Al Hamdan',
    patientAge: '35',
    patientGender: 'F',
    modality: 'MRI',
    studyName: 'Brain MRI w/wo contrast',
    doctor: 'Dr. Amira Al Nabulsi',
    clinic: 'Al Zahra Hospital',
    scheduledTime: '1:30 PM',
    status: 'Scanning',
    room: 'MRI-2 (Siemens Vida 3T)',
    progress: 55,
    eta: '~20 min remaining',
  },
  {
    accession: 'CT-20260407-002',
    patientName: 'Hassan Al Mansoori',
    patientAge: '52',
    patientGender: 'M',
    modality: 'CT',
    studyName: 'CT Chest w/ contrast',
    doctor: 'Dr. Fatima Al Mansoori',
    clinic: 'Al Noor Medical Center',
    scheduledTime: '1:45 PM',
    status: 'Scanning',
    room: 'CT-2 (Philips IQon 256)',
    progress: 78,
    eta: '~5 min remaining',
  },
  {
    accession: 'USS-20260407-003',
    patientName: 'Fatima Ibrahim',
    patientAge: '31',
    patientGender: 'F',
    modality: 'USS',
    studyName: 'Obstetric USS — 20 weeks',
    doctor: 'Dr. Mariam Al Farsi',
    clinic: 'City Hospital Dubai',
    scheduledTime: '1:50 PM',
    status: 'Scanning',
    room: 'USS-3',
    progress: 40,
    eta: '~10 min remaining',
  },
  {
    accession: 'CT-20260407-004',
    patientName: 'Mohammed Al Khalidi',
    patientAge: '48',
    patientGender: 'M',
    modality: 'CT',
    studyName: 'CT Chest w/ contrast',
    doctor: 'Dr. Fatima Al Mansoori',
    clinic: 'Pulmonology · Al Noor',
    scheduledTime: '11:30 AM',
    status: 'Scan Complete',
    room: 'CT-2',
    tat: '2.5h',
  },
  {
    accession: 'MRI-20260407-005',
    patientName: 'Aisha Al Mansoori',
    patientAge: '44',
    patientGender: 'F',
    modality: 'MRI',
    studyName: 'MRI Lumbar Spine',
    doctor: 'Dr. Rashed Al Blooshi',
    clinic: 'NMC Royal Hospital',
    scheduledTime: '9:15 AM',
    status: 'Scan Complete',
    room: 'MRI-1',
    tat: '4.8h',
  },
  {
    accession: 'MRI-20260407-006',
    patientName: 'Yousuf Al Zaabi',
    patientAge: '38',
    patientGender: 'M',
    modality: 'MRI',
    studyName: 'MRI Knee (Right)',
    doctor: 'Dr. Khaled Al Rashidi',
    clinic: 'Orthopedics · Al Zahra',
    scheduledTime: '2:30 PM',
    status: 'Scheduled',
    room: 'MRI-1',
    alerts: [],
  },
  {
    accession: 'CT-20260407-007',
    patientName: 'Mariam Al Suwaidi',
    patientAge: '58',
    patientGender: 'F',
    modality: 'CT',
    studyName: 'CT Abdomen + Pelvis',
    doctor: 'Dr. Maryam Al Sayed',
    clinic: 'Al Zahra Clinic',
    scheduledTime: '2:45 PM',
    status: 'Scheduled',
    room: 'CT-1',
    alerts: ['Contrast consent not yet signed'],
  },
  {
    accession: 'PET-20260407-008',
    patientName: 'Mohammed Al Rasheed',
    patientAge: '63',
    patientGender: 'M',
    modality: 'PET',
    studyName: 'PET-CT Full Body',
    doctor: 'Dr. Amira Al Nabulsi',
    clinic: 'Oncology · Dubai Hospital',
    scheduledTime: '3:30 PM',
    status: 'Scheduled',
    room: 'PET-1',
    alerts: ['FDG injection due at 2:30 PM'],
  },
  {
    accession: 'XR-20260407-009',
    patientName: 'Salem Al Mazrouei',
    patientAge: '29',
    patientGender: 'M',
    modality: 'X-Ray',
    studyName: 'Chest X-Ray (PA + Lateral)',
    doctor: 'Dr. Hassan Al Ali',
    clinic: 'Walk-in',
    scheduledTime: '10:00 AM',
    status: 'Released',
    room: 'XR-1',
    tat: '1.2h',
  },
  {
    accession: 'USS-20260407-010',
    patientName: 'Noura Al Hashimi',
    patientAge: '47',
    patientGender: 'F',
    modality: 'USS',
    studyName: 'Abdomen Ultrasound',
    doctor: 'Dr. Layla Al Hashimi',
    clinic: 'City Hospital Dubai',
    scheduledTime: '12:00 PM',
    status: 'Reported',
    room: 'USS-2',
    tat: '1.8h',
  },
];

export const tatChartData = [
  { name: 'Chem', lab: 2.1, radiology: 0, target: 4 },
  { name: 'Haem', lab: 1.4, radiology: 0, target: 2 },
  { name: 'Troponin', lab: 0.28, radiology: 0, target: 1 },
  { name: 'Micro', lab: 48, radiology: 0, target: 72 },
  { name: 'MRI', lab: 0, radiology: 4.8, target: 4 },
  { name: 'CT', lab: 0, radiology: 2.5, target: 3 },
  { name: 'USS', lab: 0, radiology: 1.8, target: 2 },
  { name: 'XR', lab: 0, radiology: 1.2, target: 2 },
];

export const volumeData = [
  { time: '7AM', lab: 18, radiology: 4 },
  { time: '8AM', lab: 34, radiology: 6 },
  { time: '9AM', lab: 52, radiology: 8 },
  { time: '10AM', lab: 78, radiology: 12 },
  { time: '11AM', lab: 112, radiology: 18 },
  { time: '12PM', lab: 154, radiology: 26 },
  { time: '1PM', lab: 192, radiology: 34 },
  { time: '2PM', lab: 234, radiology: 47 },
];

export const analyticsVolumeData = [
  { day: 'Mon', lab: 198, radiology: 38 },
  { day: 'Tue', lab: 221, radiology: 44 },
  { day: 'Wed', lab: 187, radiology: 41 },
  { day: 'Thu', lab: 245, radiology: 52 },
  { day: 'Fri', lab: 203, radiology: 39 },
  { day: 'Sat', lab: 167, radiology: 28 },
  { day: 'Today', lab: 234, radiology: 47 },
];

export const modalityData = [
  { name: 'MRI', value: 12, color: '#4F46E5' },
  { name: 'CT', value: 10, color: '#1D4ED8' },
  { name: 'X-Ray', value: 14, color: '#64748B' },
  { name: 'USS', value: 8, color: '#0D9488' },
  { name: 'Other', value: 3, color: '#94A3B8' },
];
